image: archlinux
packages:
  - rsync
  - arm-linux-gnueabihf-gcc-stage2
  - arm-linux-gnueabihf-glibc
  - arm-linux-gnueabihf-binutils
sources:
  - https://git.cmdline.org/~grayhatter/hudtds
tasks:
  - build: |
      cd hudtds
      pwd
      ls -la
      make
